language: php

php:
  - 7.1
  - 7.2

branches:
  only:
    - master

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - composer dump-autoload
  - pear install pear/PHP_CodeSniffer

before_install:
  - mysql -e 'CREATE DATABASE laravel_test;'

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=psr2 tests/Feature,app
