####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  sandbox-postgres-data:
    driver: local
networks:
  laravel-example:
services:
  # Postgres (10.3)
  postgres:
    image: postgres:10.3
    container_name: sandbox-postgres
    networks:
      - laravel-example
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_DB=sandbox
      - POSTGRES_USER=sandbox

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: sandbox-app
    volumes:
      - .:/var/www/app
    ports:
      - "3000:8080"
    networks:
      - laravel-example
